# Generated by Django 4.0 on 2022-02-09 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpgaCounter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='counter',
            old_name='pub_date',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='counter',
            name='question_text',
        ),
        migrations.AddField(
            model_name='counter',
            name='reading',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
