# Generated by Django 4.0 on 2022-02-09 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpgaCounter', '0002_rename_pub_date_counter_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counter',
            name='reading',
            field=models.CharField(max_length=200),
        ),
    ]
